config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'profile', to: 'profile#index'

  get 'repos', to: 'repos#index'
  get 'followers', to: 'followers#index'
  get 'following', to: 'following#index'
  get 'starred', to: 'starred#index'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following
  def initialize(screen_name, token)
    @screen_name = screen_name
    @token = token
    @path = '/following'
  end

  def other_github_users
    raw_users = service.raw_search
    raw_users.map do |user|
      OtherGithubUser.new(user)
    end
  end

  private
    attr_reader :screen_name, :path, :token

    def service
      @service ||= GithubConnectionService.new(screen_name, path, token)
    end
end

app/models/other_github_user.rb
class OtherGithubUser
  attr_reader :avatar, :name

  def initialize(attributes)
    @avatar = attributes[:avatar_url]
    @name   = attributes[:login]
  end
end

app/models/repo.rb
class Repo
  attr_reader :owner, :description, :name, :language, :stargazers_count, :forks_count

  def initialize(attributes)
    @owner            = attributes[:owner][:login]
    @description      = attributes[:description].to_s
    @name             = attributes[:name]
    @language         = attributes[:language]
    @stargazers_count = attributes[:stargazers_count]
    @forks_count      = attributes[:forks_count]
  end
end

app/models/repositories.rb
class Repositories
  def initialize(screen_name, token, path)
    @screen_name = screen_name
    @token = token
    @path = path
  end

  def user_repos
    raw_repos = service.raw_search
    raw_repos.map do |repo|
      Repo.new(repo)
    end
  end

  private
    attr_reader :screen_name, :path, :token

    def service
      @service ||= GithubConnectionService.new(screen_name, path, token)
    end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.screen_name        = auth_info.info.nickname
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/models/user_info.rb
class UserInfo
  def initialize(screen_name, token)
    @screen_name = screen_name
    @token = token
  end

  def avatar
    service1.raw_search[:avatar_url]
  end

  def following
    service1.raw_search[:following]
  end

  def followers
    service1.raw_search[:followers]
  end

  def repos
    service1.raw_search[:public_repos]
  end

  def name
    service1.raw_search[:name]
  end

  def nickname
    service1.raw_search[:login]
  end

  def starred
    service2.raw_search.count
  end

  private
    attr_reader :screen_name, :token

    def service1
      @service1 ||= GithubConnectionService.new(screen_name, path = nil, token)
    end

    def service2
      @service2 ||= GithubConnectionService.new(screen_name, '/starred', token)
    end
end

app/models/user_lists.rb
class UserLists
  def initialize(screen_name, token, path)
    @screen_name = screen_name
    @token = token
    @path = path
  end

  def other_github_users
    raw_users = service.raw_search
    raw_users.map do |user|
      OtherGithubUser.new(user)
    end
  end

  private
    attr_reader :screen_name, :path, :token

    def service
      @service ||= GithubConnectionService.new(screen_name, path, token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @github_followers = UserLists.new(session[:github_user], session[:token], '/followers')
    @user_info = UserInfo.new(session[:github_user], session[:token])
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def index
    @github_following = UserLists.new(session[:github_user], session[:token], '/following')
    @user_info = UserInfo.new(session[:github_user], session[:token])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    session[:github_user] = params[:github_user]
    @user_info = UserInfo.new(session[:github_user], session[:token])
    @github_repos = Repositories.new(session[:github_user], session[:token], '/repos')
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @github_repos = Repositories.new(session[:github_user], session[:token], '/repos')
    @user_info = UserInfo.new(session[:github_user], session[:token])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      session[:token] = request.env["omniauth.auth"]['credentials']['token']
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/starred_controller.rb
class StarredController < ApplicationController
  def index
    @github_starred = Repositories.new(session[:github_user], session[:token], '/starred')
    @user_info = UserInfo.new(session[:github_user], session[:token])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followers/index.html.erb
<div class="row">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-4">
    <%= render partial: 'layouts/profile_info' %>
  </div>
  <div class="col-lg-6">
    <div class="card text-center">
      <%= render partial: 'layouts/inner_nav' %>
      <div class="card-body">
        <% @github_followers.other_github_users.each do |github_user| %>
        <div class="card">
          <div class="card-body">
            <div class="media">
              <img class="img-thumbnail" src="<%= "#{github_user.avatar}/64x64" %>" alt="<%= "#{github_user.name}'s avatar" %>" style="width:64px">
              <div class="media-body">
                <h5 class="mt-0"><%= link_to github_user.name, profile_path(github_user: github_user.name) %></h5>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/following/index.html.erb
<div class="row">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-4">
    <%= render partial: 'layouts/profile_info' %>
  </div>
    <div class="col-lg-6">
      <div class="card text-center">
        <%= render partial: 'layouts/inner_nav' %>
        <div class="card-body">
          <% @github_following.other_github_users.each do |github_user| %>
          <div class="card">
            <div class="card-body">
              <div class="media">
                <img class="img-thumbnail" src="<%= "#{github_user.avatar}/64x64" %>" alt="<%= "#{github_user.name}'s avatar" %>" style="width:64px">
                <div class="media-body">
                  <h5 class="mt-0"><%= link_to github_user.name, profile_path %></h5>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/layouts/_inner_nav.html.erb
<div class="card-header">
  <ul class="nav nav-tabs card-header-tabs">
    <li class="nav-item">
      <%= link_to "Repositories #{@user_info.repos}", repos_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Stars #{@user_info.starred}", starred_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Followers #{@user_info.followers}", followers_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Following #{@user_info.following}", following_path, class: "nav-link active" %>
    </li>
  </ul>
</div>

app/views/layouts/_profile_info.html.erb
<img class="img-thumbnail" src="<%= "#{@user_info.avatar}/64x64" %>" alt="<%= "#{@user_info.name}'s avatar" %>" style="width:300px">
<h2><%= @user_info.name %></h2>
<h3><%= @user_info.nickname %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>APIcurious</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>

  </head>

  <body>
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">HitGub</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Pull Requests <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Issues</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Marketplace</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Explore</a>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <%= link_to 'My Profile', profile_path(github_user: current_user.screen_name), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log out', '/logout', method: :delete, class: "nav-link" %>
              </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in with GitHub', github_login_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/repos/index.html.erb
<div class="row">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-4">
    <%= render partial: 'layouts/profile_info' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <%= render partial: 'layouts/inner_nav' %>
      <div class="card-body">
        <% @github_repos.user_repos.each do |repo| %>
          <div class="card">
            <div class="card-body">
              <h3><%= repo.name %></h3>
              <p><%= repo.description %></p>
              <p><%= "#{repo.language} #{repo.forks_count} #{repo.stargazers_count}" %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/starred/index.html.erb
<div class="row">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-4">
    <%= render partial: 'layouts/profile_info' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <%= render partial: 'layouts/inner_nav' %>
      <div class="card-body">
        <% @github_starred.user_repos.each do |repo| %>
          <div class="card">
            <div class="card-body">
              <h3><%= "#{repo.owner}/#{repo.name}" %></h3>
              <p><%= repo.description %></p>
              <p><%= "#{repo.language} #{repo.forks_count} #{repo.stargazers_count}" %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-lg-4">
  </div>
  <div class="col-lg-8">
    <h1>Welcome!</h1>
    <% if current_user %>
      <p><%= link_to "Hello, #{current_user.screen_name}", profile_path %></p>
      <p><%= link_to 'View your profile', profile_path(github_user: current_user.screen_name) %></p>
    <% else %>
      <%= link_to 'Sign in with GitHub', github_login_path %>
    <% end %>
  </div>
</div>